platform :macos, '10.10'

target 'LibraryCatalog' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LibraryCatalog

  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'AlamofireImage'


end
